#!/bin/bash

# write the file info as top comments
NOW=$( date '+%F %H:%M:%S' )

printf "
/*\n\
\t template by: codetalker7\n\
\t editor: sublime text 3\n\
\t file name: $1\n\
\t date created: $NOW\n\
\t problem link: $2
*/\n\
" > $1

# append template to the file created
cat template.cpp >> $1
subl $1

